//Add a new item to the collection
POST http://localhost:3000/destinations
Content-Type: application/json
  {
    "name": "Waterloo",
    "placesToTravel": ["KWC Market", "Niagara", "Tobermory Islands"],
    "nearbyAirport": "Waterloo International Airport",
    "estimatedTravelDate": "2024-08-11"
  }

###

//Retrieve all items from the collection
GET http://localhost:3000/destinations

###

//Retrieve a single item by its ID
GET http://localhost:3000/destinations/66725ca0460e356a5dd0660d

###

//Update an item by its ID
PUT http://localhost:3000/destinations/66725ca0460e356a5dd0660d
Content-Type: application/json

{
  "name": "Toronto (Updated)",
  "placesToTravel": ["Royal Garden", "Louvre Museum", "Notre Dame Cathedral"],
  "nearbyAirport": "YYZ Airport",
  "estimatedTravelDate": "2024-08-01"
}

###

//Delete an item by its ID
DELETE http://localhost:3000/destinations/66725ca0460e356a5dd0660d